### ISSUE TITLE
The repo doesn't seem to actually contain visualizer code

### ISSUE THREAD

**Issue by sneakblock** [voxell-tech/UnityAudioVisualizer#2]
I've cloned the repo into packages (as well as tried using Unity's built in add package from the package manager), and I have only been able to find limited code and no shaders. The folder VX.Audio is completely empty, and the only .cs file I can find is WireframeGUI.cs

**Comment by sneakblock** [comment]
Nevermind, it is in the shader graph code in packages

**Comment by nixonyh** [comment]
Oh wait, that is weird, I have not included the main files for some reason in this release. Gotta fix that... in the mean time checkout v1.0.0
