### ISSUE TITLE
A little help please.

### ISSUE THREAD

**Issue by D0rk80** [voxell-tech/UnityAudioVisualizer#4]
Hello how do I get it to load after copying the files into he packages folder? Right now my viewport in unity is just the default one.
![image](https://github.com/voxell-tech/UnityAudioVisualizer/assets/40474675/f5c3533b-83d4-49b1-b154-3cdf55fcb135)

**Comment by nixonyh** [comment]
I believe there is a sample scene to import

**Comment by MahmoudAbusaqer** [comment]
> I believe there is a sample scene to import

Yes, it should be but there is not, and here is a look at all the files for the package.

![image](https://github.com/voxell-tech/UnityAudioVisualizer/assets/60627501/6cf0a844-d42f-4c81-99e4-0a591c9cd0d5)

**Comment by nixonyh** [comment]
hey, you can load the sample from the Package Manager :D

**Comment by nixonyh** [comment]
the Sample folder is supposed to be hidden in the Package so it does not get loaded into the project if not needed xD

**Comment by nixonyh** [comment]
Hey I have added a sample scene into the samples folder
